[workspace]

members = [
  "crates/liquislime-core",
  "crates/liquislime-macroquad",
  "crates/liquislime-wasmi",
]

resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/kajacx/liquislime"
license = "MIT"
